# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--config=.flake8']

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - 'types-PyYAML'

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.4.0  # The version tag you wish to use
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.0.3
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']

  - repo: local
    hooks:
      - id: validate-excluded-cves
        name: Validate Excluded CVEs
        entry: test/validate_excluded_cves.py
        language: python
        files: 'excluded_cves.yaml'
        additional_dependencies:
          - PyYAML
